name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
      run: |
        # Add pytest command when tests are created
        python -c "import main; print('Backend imports successfully')"

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false
    
    - name: Build
      working-directory: ./frontend
      run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker images
      run: |
        docker compose build
    
    - name: Test Docker compose
      timeout-minutes: 5
      run: |
        echo "=== Starting Docker Compose Debug Session ==="
        echo "Starting docker compose in detached mode..."
        docker compose up -d
        
        echo "=== Waiting for services to start ==="
        sleep 10
        
        echo "=== Checking container status ==="
        docker compose ps
        
        echo "=== System resources ==="
        df -h
        free -h
        
        echo "=== Checking backend logs ==="
        docker compose logs backend
        
        echo "=== Checking postgres logs ==="
        docker compose logs postgres
        
        echo "=== Testing health endpoint ==="
        echo "Attempting health check..."
        if curl -f -v http://localhost:8000/health; then
          echo "✓ Health check successful"
        else
          echo "✗ Health check failed"
          echo "=== Network debugging ==="
          netstat -tlnp | grep :8000 || echo "Port 8000 not listening"
          echo "=== Final container status ==="
          docker compose ps
          exit 1
        fi
        
        echo "=== Cleanup ==="
        docker compose down